#%RAML 1.0 Library
uses:
  customer: /customer.raml
  finantial: /finantial.raml
types:
  card:
    type: object
    properties:
      cardNumber:
        type: number
        required: true
        description: card number
      vigency:
        type: string
        required: false
        description: Card vigency
      cve:
        type: integer
        required: true
        description: card key security
        minimum: 3
      cardType:
        type: string
        required: false
        description: card type
      customer:
        type: customer.customer
        required: false
        description: Cliente asociado a la tarjeta
      finantialData:
        type: finantial.finantial
        required: false
        description: Datos de finanzas de la tarjeta
