#%RAML 1.0
title: "Tarjetas"
version: v0.1.0
description: Apid de Tarjetas
baseUri: http://www.miAPI.com/tarjetas/v0

uses:
  tarjeta: types/tarjeta.raml
  customer: types/customer.raml
  finantial: types/finantial.raml

/tarjetas:
  description: |
      Service for managing cards data with a specific identifier.

  get:
    description: Method for consulting card information by cardNumber
    queryParameters:
      cardNumber:
        description: |
          number of card
        type: number
        minimum: 16
        required: false
        example: 98773215987514749
    responses:
      200:
        body:
          application/json:
            #example: !include examples/cards_id/example_get200.json
            type: object
            properties:
              data:
                type: tarjeta.tarjeta
